import ApolloProvider from "@/context/apollo-server";
import Footer from "@/ui/private/footer";
import Header from "@/ui/private/header";
import { Inter } from "next/font/google";
import type { Metadata } from "next";

import "../../app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Public",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ApolloProvider>
          <main className='w-screen h-screen flex flex-col'>
            <Header />
            <div className='flex-1'>{children}</div>
            <Footer />
          </main>
        </ApolloProvider>
      </body>
    </html>
  );
}
