import Footer from "@/components/private/footer";
import Header from "@/components/private/header";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Public",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
          <div className="w-screen h-screen flex flex-col">
            <Header />
              <div className="flex-1">
                {children}
              </div>
            <Footer />
          </div>
        </body>
    </html>
  );
}
 